# highsol_train.yml
# 
# Usage: fastprop train highsol_train.yml
#
# Configuration file for training fastprop on this dataset.
# Make sure you run `prepare_data.py` first!

# training metadata
output_directory: fastprop_highsol_training
problem_type: regression
input_file: targets.csv
target_columns: logS
smiles_column: solvent_smiles
precomputed: features.csv
random_seed: 42

# network architecture
hidden_size: 3000
fnn_layers: 2

# training settings
number_epochs: 200
batch_size: 8192
patience: 20
number_repeats: 4
train_size: 0.8
val_size: 0.1
test_size: 0.1
sampler: random
